from typing import List, Optional
from backend.app.domain.repositories.task_repository import ITaskRepository
from backend.app.domain.entities.task import Task
from backend.app.infrastructure.git.git_service import GitService
from backend.app.application.dtos.task_dto import TaskCreateDTO, TaskUpdateDTO

class TaskUseCase:
    def __init__(self, task_repo: ITaskRepository, git_service: GitService):
        self.task_repo = task_repo
        self.git_service = git_service

    def list_tasks(self) -> List[Task]:
        return self.task_repo.get_all()

    def get_task(self, task_id: str) -> Optional[Task]:
        return self.task_repo.get_by_id(task_id)

    def create_task(self, dto: TaskCreateDTO) -> Task:
        # Map DTO to Entity (ID is generated by Entity default factory)
        task = Task(
            title=dto.title,
            status=dto.status,
            assignee_id=dto.assignee_id,
            start_date=dto.start_date,
            due_date=dto.due_date,
            parent_id=dto.parent_id,
            description=dto.description,
            task_type=dto.task_type,
            planned_hours=dto.planned_hours
        )
        
        saved_task = self.task_repo.save(task)
        self.git_service.commit(f"Add task {saved_task.title}")
        return saved_task

    def update_task(self, task_id: str, dto: TaskUpdateDTO) -> Optional[Task]:
        task = self.task_repo.get_by_id(task_id)
        if not task:
            return None
        
        # Update fields if provided
        update_data = dto.model_dump(exclude_unset=True)
        for key, value in update_data.items():
            setattr(task, key, value)
            
        updated_task = self.task_repo.update(task)
        self.git_service.commit(f"Update task {updated_task.title}")
        return updated_task

    def delete_task(self, task_id: str) -> bool:
        result = self.task_repo.delete(task_id)
        if result:
            self.git_service.commit(f"Delete task {task_id}")
        return result

    def undo(self) -> str:
        return self.git_service.undo()

    def redo(self) -> str:
        return self.git_service.redo()

