services:
  backend:
    build:
      context: ./backend
      target: prod
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/workspace/backend/data
    environment:
      - ENV=production

  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - "3000:80"
